version: '3.8'

services:
  app:
    build: .
    container_name: okbio-api
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./database.sqlite:/app/database.sqlite  # Mount SQLite file for persistence
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=/app/database.sqlite
      - API_URL=http://ip-api.com/json/
      - RATE_LIMIT=${RATE_LIMIT}
    restart: unless-stopped
